name: Docker

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
    strategy:
      matrix:
        platform: [amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v5
        if: success() && github.event_name != 'pull_request'
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository }}:latest-${{ matrix.platform }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=ssh://git@github.com:${{ github.repository }}.git
            org.opencontainers.image.url=https://github.com/${{ github.repository }}

      - name: Create and push manifest
        run: |
          docker manifest create \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64

          docker manifest push ghcr.io/${{ github.repository }}:${{ github.sha }}

          docker manifest create \
            ghcr.io/${{ github.repository }}:latest \
            --amend ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64

          docker manifest push ghcr.io/${{ github.repository }}:latest
