name: Validate

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format and lint
        run: |
          pip install ruff==0.7.0
          ruff format --check *.py
          ruff check *.py
